Выполнение первого ДЗ
java-park-mail-ru/card-defence-02-2017 pull request #1
Opened 2017-02-26 11:44 UTC by MaximKsh

API для регистрации. Обращения происходят с frontend сервера

2017-02-28 08:35 UTC, v1sar reviewed
Поправить замечания.

2017-02-28 08:35 UTC, v1sar commented on README.md
> +      403 - запрещено менять данные(сессия не сошлась)
Добавьте, пожалуйста, описание всего API. 
В коде есть еще как минимум метод /api/getaccount

2017-02-28 08:35 UTC, v1sar commented on src/main/java/com/kvteam/backend/AccountService.java
> +        return null;
Добавьте аннотации @Nullable, где это необходимо. (IDEA подсвечивает нужные места)

2017-02-28 08:35 UTC, v1sar commented on src/main/java/com/kvteam/backend/BackendController.java
> +// Класс UserProfile  с логином и логаутом
Такого класса в проекте нет

2017-02-28 08:35 UTC, v1sar commented on src/main/java/com/kvteam/backend/BackendController.java
> +   /* private void tryLogin(UserData userData, HttpSession session){
Удалите все лишние комментарии из кода

2017-02-28 08:35 UTC, v1sar commented on src/main/java/com/kvteam/backend/BackendController.java
> +                "";
Все ответы должны быть в JSON, даже если это ошибка. 
{ "error": "Вход запрещен" }

2017-02-28 08:35 UTC, v1sar commented on src/main/java/com/kvteam/backend/BackendController.java
> +        final UUID sessionID = accountService.login(userData.getUsername(), userData.getPassword());
При каждом логине генерируется новый UUID. 

Должна быть другая логика, Вы должны брать sessionId у пользователя. Чтобы пользователь не мог бесконечно логинится. Можно воспользоваться классом HttpSession.

2017-02-28 11:43 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/BackendController.java
> +        final UUID sessionID = accountService.login(userData.getUsername(), userData.getPassword());
При попытке залогиниться уже залогиненным будет выполнен предварительный логаут
 if(userData.getSessionID() != null) { tryLogout(...) }

2017-02-28 12:19 UTC, v1sar commented on src/main/java/com/kvteam/backend/BackendController.java
> +        final UUID sessionID = accountService.login(userData.getUsername(), userData.getPassword());
Вы перед этим делаете userData = parseUserData(body)
У вас в этом условии всегда null

Но вопрос опять же в другом - вы должны однозначно определять пользователя по sessionId, для этого вам потребуется как минимум еще одна карта.

2017-02-28 17:03 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/BackendController.java
> +        final UUID sessionID = accountService.login(userData.getUsername(), userData.getPassword());
Исправил замечания. По поводу HttpSession - мы хотим обращаться к бэкэнду с фронтэнд сервера, на который будет возложена функция шаблонизации. Сответственно, информация о пользовательской сессии будет забираться фронтэнд сервером из куки и отправкой его на бэкэнд в JSON, и наоборот, фронтэнд сервер будет отправлять клиенту ответы с заголовком сет-куки, если того потребует бэкэнд.

2017-02-28 19:26 UTC, KSolovyev requested changes
я немного еще от себя добавил

2017-02-28 19:26 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/dataformats/ResponseStatusData.java
> +    public ResponseStatusData(int c, String mess){
не надо так делать, напишите что такое `c`

2017-02-28 19:26 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/BackendController.java
> +    @RequestMapping(path = "/api/getaccount", method = RequestMethod.POST, produces = "application/json")
у вас 3 разные ручки 
POST api/getaccount
POST api/editaccount
POST api/register
предлагаю переделать в 
GET api/account
PUT api/account
POST api/account

2017-02-28 19:26 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/BackendController.java
> +            return (new Gson()).toJson(ResponseStatusData.INVALID_REQUEST);
Объекты, которые сериализуют в json, умееют кэшировать результаты анализа объектов через рефлекшен. Если вы каждый раз его заново создаете, то никакого кэширования, естественно, не происходит. Это раз
Давайте будем использовать не Gson, а встроенный Jackson. то есть возвращаете из метода ResponseEntity.ok(ResponseStatusData.SUCCESS)

2017-02-28 19:26 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/BackendController.java
> +    public String isLoggedIn(@RequestBody String body,
c jackson можно сразу будет инжектить UserData. Только надо не забыть проставить в модели аннотации `@JsonCreator` и `@JsonProperty`

2017-02-28 19:26 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/AccountService.java
> +            throw new UserAlreadyExistException();
то, что вы здесь делаете, является передачей управления через исключение. На самом деле (если не учитывать гонки между несколькими запросами) мы можем заранее посмотреть, есть ли такой пользователь. Это в общем-то не исключительная ситуация. Вот если мы посмотрели, не нашли такого же, а потом в БД случился конфликт, то да, тут исключение подходит.
Причина, почему не стоит так делать, в том, что передача управления через исключение почти в 70 раз медленнее обычного ветвления.

2017-03-01 18:31 UTC, KSolovyev commented
Если думаете, что все поправили, отпишитесь, пожалуйста

2017-03-01 19:40 UTC, KSolovyev commented
Во-первых, функцию смены логина я в интернете нигде не встречал. Она странная и от нее действительно можно отказаться.
Во-вторых, вы почему-то привязались к этому Account'у. Привяжитесь лучше к сервису. Добавьте  туда метод editCreditionals(userId, login, password, email) и сделайте все операции в нем. Только не забудьте проверить, что пользователь действительно есть.

2017-03-01 20:19 UTC, d-frolov reviewed
По всему коду: пожалуйста, сделайте везде автоформат кода. Идея красиво отформатирует и потом легче будет разбираться ченджсетах

2017-03-01 20:19 UTC, d-frolov commented on src/main/java/com/kvteam/backend/AccountService.java
> +import com.sun.istack.internal.NotNull;
Очень здорово, что вы используете такие аннотации, но рекомендую вам заменить их
на аннотации org.jetbrains.annotations 13-х версии. Они лучше поддерживаются Идеей

2017-03-01 22:02 UTC, MaximKsh commented
Функции смены логина нет в текущем варианте API. editAccount изменяет почту, пароль в том случае, если username и sessionID сходятся с указанными на сервере(пользователь залогинен и от своего имени изменяет данные).
Вся работа из контроллера привязана к сервису AccountService. AccountService представляет из себя необходимый функционал для работы с пользователями как с коллекцией, а именно проверка наличия юзера. Далее UserAccount инкапсулирует в себе методы для работы с конкретным пользователем. Соответственно, от самого контролера это все скрыто, интерфейс для работы с пользователями предоставляет AccountService и вся работа идет через него. Внутри же функционал работы с коллекцией и с конкретным пользователем просто разбит на два класса
По замечаниям все исправлено, по пунктам, указанным на портале реализовано все, кроме 5, так как мы хотим вынести часть клиентского кода на фронтэнд сервер и выполнять обращение к API с него, значит кроссдоменные запросы и пользовательские сессии не затрагиваются.
Алгоритм работы с сессиями предполагается таковым, что пользователь отправляет запрос на сервер фронтэнда, сервер фронтэнда берет из кук username и sessionID, запаковывает в JSON и отправляет на бэкэнд сервер. Бэкэнд сервер отвечает JSON  с необходимыми данными, фронтэнд выполняет на основе этих данных шаблонизацию страницы и возвращает клиенту(при необходимости добавляя заголовки Set-Cookie. Например, случай, когда пользователь хочет выполнить logout: клиент отправляет запрос фронтэнд севреру, фронтэнд достает из куки username, sessionID и отсылает на бэкэнд. На бэкэнде вызывается метод logout, возвращается 200 код, фронтэнд возвращает страницу для незарегистрированных пользователей с заголовком на очистку куки.

2017-03-02 07:29 UTC, KSolovyev commented
1. Редактирование имени пользователя и не надо было делать. Этого никто в интернете не делает
2. CORS  понадобится для web socket'ов. Без него не заработает
3. Учтите, что web socket'ы должны будут соединяться напрямую. Схема с проксирующим соединением сложна. Для этого вам придется на фронт пробрасывать данные сессии и адрес сервера. Чтобы вебсокет тоже "узнал" конкретного пользователя. В общем делайте, как хотите, но будет попоболь в 3-ем модуле. Я обещаю

2017-03-12 19:08 UTC, KSolovyev requested changes

2017-03-12 19:08 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/AccountService.java
> +            final UserAccount acc = users.get(username);
А в чем смысл разделения на UserAccount и UserData?

2017-03-12 19:59 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/AccountService.java
> +            final UserAccount acc = users.get(username);
UserData - контракт взаимодействия между клиентом и сервером.
UserAccount - имитация уровня модели (т.к. еще нет бд), в себе дополнительно хранит ID сессии и реализует логику по созданию сессии(выделение нового ID), а так же реализует элемент безопасности, не давая, к примеру, изменять данные о пользователе, если сессия сейчас не от этого пользователя

2017-03-13 20:35 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/AccountService.java
> +            final UserAccount acc = users.get(username);
Ок, но у вас в этой модели еще и контроллер. Это вызовет проблемы, когда добавится база

2017-03-14 06:01 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/AccountService.java
> +            final UserAccount acc = users.get(username);
Когда добавится база (скорее всего в выходные после лекции на этой неделе) класс UserAccount будет сильно изменен, и часть логики ляжет на субд(выделение нового id сессии, например), а часть в accountService

2017-03-16 16:12 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/AccountService.java
> +            final UserAccount acc = users.get(username);
ок, посмотрим

2017-03-16 16:18 UTC, merged