Игровая  механика
java-park-mail-ru/card-defence-02-2017 pull request #3
Opened 2017-04-15 15:23 UTC by MaximKsh

Работают сокеты, разделение на сингл и мульти, форматы сообщений клиент-сервер. Настройки матча и карты тянуться с json-файла. Просчет сделан только для первого хода и довольно примитивно

2017-04-17 14:55 UTC, KSolovyev commented
добавьте в описание ссылку, куда деплоится CI фронта, пожалуйста

2017-04-17 15:14 UTC, MaximKsh commented
Добавил

2017-04-17 15:29 UTC, KSolovyev requested changes
Еще не все

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/AppConfiguration.java
> +            final Card[] cards = objectMapper()
давайте через систему ресурсов будем это делать

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/websockets/CheckCredentialsWebsocketInterceptor.java
> +                            .split(VARIABLE_DELIMITER))
в ручную парсить параметры запроса - гиблое дело. Если уж хотите этим заняться, найдите себе библиотеку

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/websockets/CheckCredentialsWebsocketInterceptor.java
> +                    && request.getURI().getQuery().length() < MAX_QUERY_LENGTH) {
Странная и опасная проверка. Почему именно 50? А не 2 или 16?

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/websockets/CheckCredentialsWebsocketInterceptor.java
> +                    // Может возникнуть при разборе query параметров
мы не разобрали query параметры, и что дальше делаем? Ничего, просто молча глотаем исключение? Мы ведь дальше работать не сможем

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/websockets/GameWebSocketHandler.java
> +            singleplayerHubService.addPlayer(connection);
вот тут вы добавляете в специальный сервис соединение, но я не нашел, где вы его удаляете

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/websockets/PlayerConnection.java
> +        onReceiveEvent = event;
вот тут мы всегда делаем одно и тоже. Может быть подумаем, как без лямбд и консьюмеров обойтись?

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/websockets/GameWebSocketHandler.java
> +    private Map<String, IPlayerConnection> connections =
вот эта штука должна быть ConcurrentHashMap

2017-04-17 15:29 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/GameService.java
> +    private void receive(
Вот эта функция будет исполняться из нескольких потоков. И будут гонки с startGame. Вы не хотите использовать тот патерн, что я показывал, через потокобезопасную очередь?

2017-04-17 15:40 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/websockets/GameWebSocketHandler.java
> +            singleplayerHubService.addPlayer(connection);
Добавление в singleplayerHubService и matchmakingService не напрямую означает добавление в какие-либо контейнеры. Алгоритм таков, в addPlayer передается подключение игрока, потом в методе ищется возможный противник, если находится, то оба соединения передаются в gameService.

2017-04-17 15:44 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/websockets/CheckCredentialsWebsocketInterceptor.java
> +                    // Может возникнуть при разборе query параметров
allowConnect будет false в случае исключения и соединение будет сброшено. (т.к. это происходит в случае неправильных входных параметров, которые заранее определены, то, скорее всего, кто-то пытается подключиться по вебсокету в обход вшитой в клиент логики, такого можно проигнорировать)

2017-04-17 15:49 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/websockets/CheckCredentialsWebsocketInterceptor.java
> +                    && request.getURI().getQuery().length() < MAX_QUERY_LENGTH) {
Заранее определено конечное множество значений get параметров. Самая длинная возможная строка при этом "type=multiplayer&side=defence", длина строки получается 29, и, этого было бы достаточно. Заменю на более короткое значение

2017-04-17 21:49 UTC, KSolovyev commented
А можно еще ссылку в описание pull request'a?

2017-04-18 10:04 UTC, MaximKsh commented
Обновил описание пул реквеста

2017-04-18 10:09 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/websockets/GameWebSocketHandler.java
> +    private Map<String, IPlayerConnection> connections =
Поправил

2017-04-18 21:07 UTC, KSolovyev commented
советую написать пару тестов =)

2017-04-23 20:42 UTC, MaximKsh commented
Добавил просчет игровой логики, плюс хранение игровых данный в оперативке и запись в базу в отдельных потоках

2017-04-24 20:41 UTC, MaximKsh commented
Добавил тесты

2017-04-24 20:51 UTC, KSolovyev commented
а фронт еще не играбелен? =(

2017-04-24 20:53 UTC, KSolovyev requested changes

2017-04-24 20:53 UTC, KSolovyev commented on src/test/java/com/kvteam/backend/services/GameTestWebSocketSession.java
> +public class GameTestWebSocketSession implements WebSocketSession {
Почему mockito не используете?

2017-04-25 05:32 UTC, MaximKsh commented
Фронт, к сожалению, к четвергу не успеем сделать

2017-04-25 06:38 UTC, MaximKsh commented on src/test/java/com/kvteam/backend/services/GameTestWebSocketSession.java
> +public class GameTestWebSocketSession implements WebSocketSession {
```
private String lastReceivedString;
private boolean forceClose = false;
public String getLastReceivedString(){
        return lastReceivedString;
}
``````

@Override
public void sendMessage(WebSocketMessage<?> webSocketMessage) throws IOException {
        lastReceivedString = webSocketMessage.getPayload().toString();
}
```

Интерфейс был чуть-чуть расширен для удобного получения отправленных тестируемым классом данных. При вызове sendMessage внутри тестируемого класса у WebSocketSession меняется только внутреннее состояние(отправленное сообщение, нужно его запомнить), а затем уже в методе-тесте достаем из сессии отправленное сообщение.

2017-05-02 22:19 UTC, KSolovyev requested changes
код хороший, но хочется больше игровых тестов.
Ждем интеграцию с фронтом

2017-05-02 22:19 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/gameplay/MoveProcessor.java
> +        }
nice

2017-05-02 22:19 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/gameplay/MoveProcessor.java
> +            }else{
return, else не нужен

2017-05-02 22:19 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/GameDbService.java
> +public class GameDbService {
вы все-таки решили сделать ходы персистентными. Я бы хотел услышать обоснование такого решения. Зачем вам это?

2017-05-05 19:27 UTC, MaximKsh commented
Поправил отдачу юнитов для рассчитаного хода: отдельно свои, отдельно чужие. По поводу персистентности отдельных ходов хотел бы сказать, что мы немного пересмотрели необходимость их хранения. На текущем этапе ходы также асинхронно сохраняются в базу, но после в процессе игры не загружаются. Это может быть полезным для некоторых причин: можно будет отслеживать ход каждый игры, для поиска багов или хаков, собирать статистику по игровым ситуациям и возможность реплеев. В рамках курса, к сожалению, это будет реализовать трудно ввиду уже ограниченности времени.
Фронтэнд, скорее всего, будет реализован к следующей лекции (11.05)

2017-05-09 10:27 UTC, KSolovyev commented
Ок, тогда посмотрю в четверг

2017-05-11 10:31 UTC, KSolovyev commented
фронт готов?

2017-05-15 14:10 UTC, KSolovyev commented
@MaximKsh отпишитесь, как будет фронт готов

2017-05-22 09:44 UTC, MaximKsh commented
Фронт пока с багами, но сыграть мультиплеер уже можно (сингл пока адаптируем). Там в настройках стоит два хода и очень плохой игровой баланс :)
https://tp-frontend-kv.herokuapp.com/

2017-05-23 11:08 UTC, KSolovyev commented
Ок, остальное в следующем пул реквесте. Сосредоточьтесь на нескольких ходах в мультиплеере

2017-05-23 11:09 UTC, merged