РК 4
java-park-mail-ru/card-defence-02-2017 pull request #4
Opened 2017-05-23 20:54 UTC by MaximKsh

Таймаут на выбор карт перед ходом. Величина таймаута устанавливается в json конфиге, если не указано, таймаут не используется. Если игрок не успевает за ограниченное время, то игрока заканчивается с победой того, кто успел.

2017-06-01 22:08 UTC, KSolovyev requested changes

2017-06-01 22:08 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/GameService.java
> +            e.printStackTrace();
через логгер такие вещи пишите, пожалуйста

2017-06-01 22:08 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +                }while(!timeouts.isEmpty() && !(pair = timeouts.poll()).equals(firstPair));
А если первый таймаут сработал, то мы будем крутиться в цикле, пока все таймауты не закончатся, да?

2017-06-01 22:08 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +            semaphore = new Semaphore(1);
ну зачем, зачем вы пишите какие-то ручные семафоры??? Ну ведь точно набажили с ними

2017-06-01 22:08 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +                }while(!timeouts.isEmpty() && !(pair = timeouts.poll()).equals(firstPair));
и все это со взятым локом, с которым добавить новый таймаут нельзя. А значит и все игры тоже встанут

2017-06-01 22:08 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +            return (attacker.toString() + defender.toString()).hashCode();
=(((

2017-06-02 07:49 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/services/GameService.java
> +            e.printStackTrace();
Поправил

2017-06-02 08:12 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +                }while(!timeouts.isEmpty() && !(pair = timeouts.poll()).equals(firstPair));
Поправил алгоритм. Локов на момент проверки таймаутов нет

2017-06-02 08:13 UTC, MaximKsh commented
Пулл реквест висит 10 дней, а замечания за день до защиты :(

2017-06-02 08:57 UTC, KSolovyev commented
Да, есть такое

2017-06-02 10:09 UTC, KSolovyev requested changes

2017-06-02 10:09 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +            final LinkedList<TimeoutConnectionPair> newTimeouts = new LinkedList<>();
такие штуки лучше делать через TreeMap. Хранить таймауты в отсортированной коллекции. Идея была в задачке, которую я давал https://github.com/java-park-mail-ru/rk2_cases/tree/master/exploders/src

2017-06-02 11:04 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +            final LinkedList<TimeoutConnectionPair> newTimeouts = new LinkedList<>();
Переделал

2017-06-02 13:31 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +            timedOut.forEach((k, v) -> timeouts.remove(k, v));
вот здесь можно вместо удаления брать tailMap

2017-06-02 18:33 UTC, MaximKsh commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +            timedOut.forEach((k, v) -> timeouts.remove(k, v));
Очищая timedOut можно удалять элементы из исходного timeouts

2017-06-02 20:57 UTC, KSolovyev commented on src/main/java/com/kvteam/backend/services/TimeoutService.java
> +            timedOut.forEach((k, v) -> timeouts.remove(k, v));
👍

2017-06-02 20:58 UTC, merged